name: frl_boilerplate
description: Boilerplate code generator for Clean Architecture in Flutter
version: 1.0.0
repository: https://github.com/username/frl_boilerplate
homepage: https://github.com/username/frl_boilerplate
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  auto_route_generator: any
  awesome_dio_interceptor: any
  build_runner: any
  freezed: any
  injectable_generator: any
  lints: ^5.0.0
  test: ^1.24.0

dependencies:
  auto_route: any
  connectivity_plus: any
  dartz: any
  data_channel: any
  dio: any
  freezed_annotation: any
  get_it: any
  injectable: any
  intl: any
  json_annotation: any
  json_serializable: any
  path: any
  path_provider: any
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

executables:
  frl_boilerplate: frl_boilerplate
