name: frl_boilerplate
description: Boilerplate code generator for Clean Architecture in Flutter
version: 1.0.0
repository: https://github.com/efrilm/frl-boilerplate-flutter
homepage: https://github.com/efrilm/frl-boilerplate-flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  auto_route_generator: ^10.2.3
  awesome_dio_interceptor: ^1.3.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.1.0
  injectable_generator: ^2.7.0
  lints: ^5.0.0
  test: ^1.24.0

dependencies:
  auto_route: ^10.1.0+1
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  data_channel: ^2.0.0+1
  dio: ^5.8.0+1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  path: ^1.9.1
  path_provider: ^2.1.5
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

executables:
  frl_boilerplate: frl_boilerplate
flutter_gen:
  output: lib/shared/assets/
  integrations:
    flutter_svg: true
