name: frl_boilerplate
description: Boilerplate code generator for Clean Architecture in Flutter
version: 1.0.0
repository: https://github.com/efrilm/frl-boilerplate-flutter
homepage: https://github.com/efrilm/frl-boilerplate-flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependencies:
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

executables:
  frl_boilerplate: frl_boilerplate
